name: Daily Digest

on:
  schedule:
    - cron: "0 5 * * *"  # 05:00 UTC ежедневно
  workflow_dispatch:
    inputs:
      message_suffix:
        description: "Добавить к заголовку (опционально)"
        required: false
        default: ""
      override_dnd:
        description: "Игнорировать тихие часы"
        required: false
        default: "false"

permissions:
  contents: read

jobs:
  digest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run digest
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          MESSAGE_SUFFIX: ${{ inputs.message_suffix }}
          OVERRIDE_DND: ${{ inputs.override_dnd }}
        run: |
          python digest.py --config config.json
